# Site settings
title: Onur Rauf Bingöl
email: orbingol@gmail.com
description: "Kişisel blogum..."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://onurraufbingol.com" # the base hostname & protocol for your site
twitter_username: orbingol
github_username:  orbingol

# Default permalink style
permalink: /:year/:month/:day/:title.html

# Build settings
markdown: kramdown
highlighter: pygments

# Use the following plug-ins
gems:
- jemoji # Emoji please!
- jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Default encoding
encoding: "utf-8"

# Extension handling
markdown_ext: "markdown,md,html"
textile_ext: "textile"

# Exclude these files from your production _site
exclude:
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- CNAME
